services:
  # Aplicação principal
  market-dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: market-dashboard-app
    ports:
      - "0.0.0.0:3050:3050"  # Permite acesso externo
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço de desenvolvimento (opcional)
  market-dashboard-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: market-dashboard-dev
    ports:
      - "0.0.0.0:3051:3050"  # Permite acesso externo
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev

networks:
  default:
    name: market-dashboard-network
